/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bit.map.transformer;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {

        System.out.println(Arrays.toString(args));

        Bitmap newBitmap = new Bitmap(args[0], args[1]);
    }
}
